services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - ft_onion_net
  
  tor:
    container_name: tor
    build: ./tor
    ports:
      - "9001:9001"
    networks:
      - ft_onion_net

  ssh:
    container_name: ssh
    build: ./ssh
    ports:
      - "4242:4242"
    networks:
      - ft_onion_net

networks:
  ft_onion_net:
    driver: bridge