services:
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - ft_onion_net
  
  tor:
    container_name: tor
    build: ./tor
    depends_on:
      - nginx
      - ssh
    volumes:
      - tor_data:/var/lib/tor/hidden_service
    networks:
      - ft_onion_net

  ssh:
    container_name: ssh
    build: ./ssh
    networks:
      - ft_onion_net
    volumes:
      -  ${HOME}/.ssh/id_ed25519.pub:/home/user/.ssh/authorized_keys:ro

volumes:
  tor_data:

networks:
  ft_onion_net:
    driver: bridge